# datastax standard .kube-linter.yaml
checks:
  doNotAutoAddDefaults: true
  include:

    # recommended deaults by kube-linter
    # - "dangling-service"
    # - "deprecated-service-account-field"
    # - "docker-sock"
    # - "drop-net-raw-capability"
    # - "env-var-secret"
    # - "host-ipc"
    # - "host-network"
    # - "host-pid"
    # - "latest-tag"
    # - "mismatching-selector"
    # - "no-anti-affinity"
    # - "no-extensions-v1beta"
    # - "no-read-only-root-fs"
    # - "non-existent-service-account"
    # - "privilege-escalation-container"
    # - "privileged-container"
    # - "run-as-non-root"
    # - "sensitive-host-mounts"
    # - "ssh-port"
    # - "unsafe-sysctls"
    # - "unset-cpu-requirements"
    # - "unset-memory-requirements" 

    # enabled by Datastax      
    - "no-liveness-probe"
    - "no-readiness-probe"
    - "no-rolling-update-strategy"