name: Snyk javascript scan
description: Snyk javascript scan
inputs:
  python-version:
    required: true
    description: "python version"
  directories:
    required: true
    description: "directories of python modules"
  SNYK_TOKEN:
    required: true
    description: "SNYK_TOKEN"
  SNYK_ORG_ID:
    required: true
    description: "SNYK_ORG_ID"
  extra-snyk-options:
    required: false
    description: "extra snyk option that pass to snyk"

runs:
  using: "composite"
  steps:
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    
    - name: Scan python projects 
      shell: bash
      env:
        SNYK_TOKEN: ${{ inputs.SNYK_TOKEN }}
        SNYK_ORG_ID: ${{ inputs.SNYK_ORG_ID }}
      run: |
        dirs="${{ inputs.directories }}"
        dirs=$(echo $dirs | tr ", " "\n")

        for d in $dirs; do
          cd $GITHUB_WORKSPACE/$d
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          snyk monitor --command=venv/bin/python --org=${SNYK_ORG_ID} --file=requirements.txt ${{ inputs.extra-snyk-options }} \
            ${SNYK_GROUP_OPTS} ${SNYK_TAGS} --policy-path=$GITHUB_WORKSPACE
    
        done