name: Snyk process scan result
description: construct snyk scan result message and comment on PR

inputs:
   gh_repo_token:
     required: true
     description: "github token used for add comment for PR"

runs:
  using: "composite"
  steps:
    - name: Construct snyk scan comments
      shell: bash    
      run : |
        snyk_url="https://app.snyk.io/org/riptano/projects"
        snyk_site="Please see scan report at: <a href=\'${snyk_url}\'>${snyk_url}</a>"
        good_msg="✅ snyk scan did not find issues with severity level <b><i>${{ env.SNYK_SEVERITY_THRESHOLD_LEVEL }}</i></b> or higher. $snyk_site"
        bad_msg="🚫 snyk scan found issues with severity level <b><i>${{ env.SNYK_SEVERITY_THRESHOLD_LEVEL }}</i></b> or higher! $snyk_site"
        
        if [[ $SNYK_TEST_PASSED == 'true' ]]; then           
          echo "SNYK_SCAN_COMMENT=$good_msg" >> $GITHUB_ENV 
        else
          echo "SNYK_SCAN_COMMENT=$bad_msg" >> $GITHUB_ENV 
        fi

    - name: Set pull request comment
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ inputs.gh_repo_token }}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '${{ env.SNYK_SCAN_COMMENT }}'
          })

    - name: Decision for the snyk an result, (PR gating if triggered for a PR)
      run: |
        echo "$SNYK_SCAN_COMMENT" 
        if [[ "$SNYK_TEST_PASSED" != 'true' ]]; then
          exit 1 
        fi