name: "act 1 name"
description: "act 1 des"
inputs:
   a1_input_1:
     required: true
     description: "a1_input_1"
   a1_input_2:
     required: false
     description: "a1_input_2"
runs:
  using: "composite"
  steps:
    - name: set env 1
      env:
        e1: e1_v1
        a2: ${{ inputs.a1_input_2 }}
      run: |
        echo "in set env 1"
        echo "e1 is [$e1]"
        echo "MEMEME1=${{ inputs.a1_input_1 }}" >> $GITHUB_ENV 
        if [[ "${{ inputs.a1_input_2 }}" != "" ]]; then
          echo '\$ {{ inputs.a1_input_2 }}" != ""'
        fi
        echo '[${{ inputs.a1_input_2 }}]'
        
        append="s"
        if [[ "${{ inputs.a1_input_2 }}" != "" ]]; then
          append="/${{ inputs.a1_input_2 }}"
        fi
        echo "append is [$append]"
        snyk_url="https://app.snyk.io/org/riptano/project${append}"
        echo "snyk_url is [$snyk_url]"
      shell: bash
