name: Snyk node scan
description: Snyk node scan
inputs:
  node-version:
    required: true
    description: "node version"
  directories:
    required: true
    description: "directories of node modules"
  SNYK_TOKEN:
    required: true
    description: "SNYK_TOKEN"
  SNYK_ORG_ID:
    required: true
    description: "SNYK_ORG_ID"
  extra-snyk-options:
    required: false
    description: "extra snyk option that pass to snyk"

runs:
  using: "composite"
  steps:
    - name: Set up node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
    
    - name: Scan node projects 
      shell: bash
      env:
        SNYK_TOKEN: ${{ inputs.SNYK_TOKEN }}
        SNYK_ORG_ID: ${{ inputs.SNYK_ORG_ID }}
      run: |
        dirs="${{ inputs.directories }}"
        dirs=$(echo $dirs | tr ", " "\n")

        for d in $dirs; do
          cd $GITHUB_WORKSPACE/$d
          npm install
          snyk monitor --org=${SNYK_ORG_ID} --file=package.json ${{ inputs.extra-snyk-options }} \
            ${SNYK_GROUP_OPTS} ${SNYK_TAGS} --policy-path=$GITHUB_WORKSPACE
    
        done