name: Snyk set up
description: Set up repo branch names (repo_branch) and tags for snyk
inputs:
   python-version:
     required: true
     description: "python version"
   directories:
     required: true
     description: "directories of python modules"
   SNYK_TOKEN:
     required: true
     description: "SNYK_TOKEN"
   SNYK_ORG_ID:
     required: true
     description: "SNYK_ORG_ID"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    
    - name: set up python vevn and requirement
      shell: bash
      env:
        SNYK_TOKEN: ${{ inputs.SNYK_TOKEN }}
        SNYK_ORG_ID: ${{ inputs.SNYK_ORG_ID }}
      run: |
        dirs="${{ inputs.directories }}"
        dirs=$(echo $dirs | tr ", " "\n")

        for d in $dirs; do
          cd $GITHUB_WORKSPACE/$d
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          snyk monitor --command=venv/bin/python --org=${SNYK_ORG_ID} --file=requirements.txt \
            ${SNYK_GROUP_OPTS} ${SNYK_TAGS} --policy-path=$GITHUB_WORKSPACE
    
          snyk test --command=venv/bin/python --org=${SNYK_ORG_ID} --file=requirements.txt \
            ${SNYK_SEVERITY_THRESHOLD} --policy-path=$GITHUB_WORKSPACE  \
            || echo "SNYK_TEST_PASSED=false" >> $GITHUB_ENV
        done