name: Snyk javascript scan
description: Snyk javascript scan
inputs:
   javascript-version:
     required: true
     description: "javascript version"
   directories:
     required: true
     description: "directories of javascript modules"
   SNYK_TOKEN:
     required: true
     description: "SNYK_TOKEN"
   SNYK_ORG_ID:
     required: true
     description: "SNYK_ORG_ID"

runs:
  using: "composite"
  steps:
    - name: Set up javascript
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.javascript-version }}
    
    - name: Scan javascript projects 
      shell: bash
      env:
        SNYK_TOKEN: ${{ inputs.SNYK_TOKEN }}
        SNYK_ORG_ID: ${{ inputs.SNYK_ORG_ID }}
      run: |
        dirs="${{ inputs.directories }}"
        dirs=$(echo $dirs | tr ", " "\n")

        for d in $dirs; do
          npm install
          snyk monitor --org=${SNYK_ORG_ID} --file=package.json \
            ${SNYK_GROUP_OPTS} ${SNYK_TAGS} --policy-path=$GITHUB_WORKSPACE
    
          snyk test --org=${SNYK_ORG_ID} --file=package.json \
            ${SNYK_SEVERITY_THRESHOLD} --policy-path=$GITHUB_WORKSPACE  \
            || echo "SNYK_TEST_PASSED=false" >> $GITHUB_ENV
        done