name: Snyk java scan
description: Snyk java scan (including simple maven and gradle)
inputs:
   java-version:
     required: true
     description: "java version"
   directories:
     required: true
     description: "directories of maven modules"
   SNYK_TOKEN:
     required: true
     description: "SNYK_TOKEN"
   SNYK_ORG_ID:
     required: true
     description: "SNYK_ORG_ID"

runs:
  using: "composite"
  steps:
    - name: Set up java
      uses: actions/setup-java@v2
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        cache: maven    

    - name: Scan maven projects 
      shell: bash
      env:
        SNYK_TOKEN: ${{ inputs.SNYK_TOKEN }}
        SNYK_ORG_ID: ${{ inputs.SNYK_ORG_ID }}
      run: |
        dirs="${{ inputs.directories }}"
        dirs=$(echo $dirs | tr ", " "\n")

        for d in $dirs; do
          cd $GITHUB_WORKSPACE/$d
          snyk monitor -DskipTests --org=${SNYK_ORG_ID} --all-projects \
            ${SNYK_GROUP_OPTS} ${SNYK_TAGS} --policy-path=$GITHUB_WORKSPACE

          snyk test -DskipTests --org=${SNYK_ORG_ID} --all-projects \
            ${SNYK_SEVERITY_THRESHOLD} --policy-path=$GITHUB_WORKSPACE  \
            || echo "SNYK_TEST_PASSED=false" >> $GITHUB_ENV                  
        done