name: 🏷️ snyk test and push to ecr
on: 
  workflow_dispatch: 
    inputs:
      image_with_tag:
        description: 'fully qualified image repo with tag,e.g. python:alpine3.15'
        required: true

env:
  ECR_URL: 237073351946.dkr.ecr.us-east-1.amazonaws.com  
  DOCKER_REPO_PREFIX: datastax/astra-commercial
  DOCKER_REPO_WITH_TAG: ${{ inputs.image_with_tag }}
  SNYK_SEVERITY_THRESHOLD_LEVEL: critical

jobs: 
  snyk-test-and-push-to-ecr:
    runs-on: ubuntu-latest
    steps:
      - name: pull docker image from thirdparty site
        run: |
          docker pull $DOCKER_REPO_WITH_TAG
      - name: Set up Snyk
        uses: snyk/actions/setup@master 

      - name: run snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_ORG_ID: ${{ secrets.SNYK_ORG_ID }}          
        run: |
          snyk container test $DOCKER_REPO_WITH_TAG --severity-threshold=$SNYK_SEVERITY_THRESHOLD_LEVEL
      - name: login to ecr and push the image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DMC_CLOUD_TOOL_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DMC_CLOUD_TOOL_SEC_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'  
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_URL 
          name=$(echo $DOCKER_REPO_WITH_TAG | cut -d ':' -f 1)
          repoName=$DOCKER_REPO_PREFIX/$name
          echo "repoName: [$repoName]"
          aws ecr describe-repositories --repository-names $repoName \
            || aws ecr create-repository --repository-name $repoName --image-tag-mutability IMMUTABLE
          docker tag $DOCKER_REPO_WITH_TAG $ECR_URL/$DOCKER_REPO_PREFIX/$DOCKER_REPO_WITH_TAG   
          docker push $ECR_URL/$DOCKER_REPO_PREFIX/$DOCKER_REPO_WITH_TAG     
